branch-defaults:
  master:
    environment: expressapp-dev
global:
  application_name: expressapp
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  profile: null
  sc: git
